### PR TITLE
Update dependencies, Migrate to 2018 edition

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

- Migrate to 2018 edition
- Update dependencies

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
LGTM :+1:

Should we add a [minimum `rustc` version](https://docs.travis-ci.com/user/languages/rust/#choosing-a-rust-version) to `travis.yml` while we're at it? From memory, the 2018 edition came out around 1.32 or so.

**Comment by koushiro** [comment]
@Michael-F-Bryan I have added **MSRV** into `.traivs.yml`. PTAL again :)

**Comment by koushiro** [comment]
It would be nice of you to release a new version so that downstream users can gradually get rid of syn 0.15 in their crate graph.

**Comment by Michael-F-Bryan** [comment]
Version 0.2.0 [is now on crates.io](https://crates.io/crates/slog-derive) :tada:

**Comment by koushiro** [comment]
Awesome!

**Pull request merged**
